baseURL = 'https://simplydelicio.us/'
languageCode = 'en-us'
title = 'SimplyDelicio.us'
theme = "recipes"

[pagination]
  pagerSize = 16

[params]
  logo = "/logo.png"
  author = "simplydelicio.us"
  description = "Simple and Delicious Recipes"